#!/bin/sh

############## ### created by Daniel Tigges
##
#	Parameter = -1	| MAIN  |  |  EXT  |
#	Parameter = 0	|  EXT  |
#	Parameter = 1	|  EXT  |  | MAIN |
#	Parameter = 2	|  MAIN |
##
###
#############

MAIN="LVDS-1"
CONNECTED=$(xrandr -q | grep " connected" | grep -v "$MAIN" | cut -d ' ' -f1)
NR_MON=$(xrandr -q | grep " connected" | cut -d ' ' -f1 | wc -l)
options="--output $MAIN --auto"

# exit if more than two monitors connected
if [ "$NR_MON" -gt 2 ]; then
    echo "More than two monitors connected. Exiting..."
    exit
fi

# exit if one monitor connected and you try to extend display
if [ "$1" != 2 ] && [ "$NR_MON" -eq 1 ]; then
    echo "More than one monitor or no external connected. Please configure it manually."
    exit
fi

if [ "$1" -eq 1 ]; then
    echo Extending display "$CONNECTED" to the left of "$MAIN"
    options="${options} --output ${CONNECTED} --auto --primary --left-of ${MAIN}"
elif [ "$1" -eq -1 ]; then
    echo Extending display "$CONNECTED" to the right of "$MAIN"
    options="${options} --output $CONNECTED --auto --primary --right-of $MAIN"
elif [ "$1" -eq 2 ]; then
    echo "Only primary display $MAIN"
    if [ -z "$CONNECTED" ]; then
 		options="$options --primary"
    else
 		options="$options --primary --output $CONNECTED --off"
    fi
elif [ "$1" -eq 0 ]; then
    echo "Only secondary display $CONNECTED"
    options="--output $MAIN --off --output $CONNECTED --auto --primary"
fi

# set monitor settings
xrandr ${options}

# set background
set-background
