#!/bin/sh

intern=LVDS-1

VGA_CON=`xrandr -q | grep 'VGA-1 connected'`
HDMI_CON=`xrandr -q | grep 'DP-1 connected'`
# if the external monitor is connected, then we tell XRANDR to set up monitor as primary
if [ -n "$VGA_CON" ] || [ ! "$VGA_CON" = "" ]; then
    xrandr --output $intern --off --output DP2 --auto --primary
elif [ -n "$HDMI_CON" ] || [ ! "$HDMI_CON" = "" ]; then
    xrandr --output $intern --off --output DP2-2 --primary --auto
else
    xrandr --output $intern --primary --auto --output DP2 --off --output DP2-2 --off
fi

exit 0;
