#!/bin/sh

MAIN="LVDS-1"
CONNECTED=$(xrandr -q | grep " connected" | grep -v "$MAIN" | cut -d ' ' -f1)
NR_MON=$(xrandr -q | grep " connected" | cut -d ' ' -f1 | wc -l)

if [ "$NR_MON" -eq 2 ]; then
	echo "Activating $CONNECTED"
    xrandr --output "$MAIN" --off --output "$CONNECTED" --auto --primary
else
	echo "Activating $MAIN"
    xrandr --output "$MAIN" --primary --auto
fi
