#!/bin/sh

# Parameter 1: process name

pid=$(pgrep -x "$1")
if [ -z $pid ]; then
	$1 &
else
	if [ $1 = "spotify" ]; then
		i3-msg "workspace "
	elif [ $1 = "thunderbird" ]; then
		i3-msg "workspace "
	elif [ $1 = "hexchat" ]; then
		i3-msg "workspace "
	fi
	#i3-msg "[class=$2] focus mode_toggle"
fi
