#!/bin/sh

volume=$1
sink=$(pactl list sinks | grep "Sink #" | grep -o '[0-9]*')

if [ "$volume" -eq 0 ]; then
    pactl set-sink-mute "$sink" toggle
elif [ "$volume" -eq -1 ]; then
   pactl set-sink-volume "$sink" -5%
elif [ "$volume" -eq 1 ]; then
   pactl set-sink-volume "$sink" +5%
fi

# send signal to i3blocks
pkill -RTMIN+10 i3blocks
