#!/bin/sh
alias dotfiles="/usr/bin/git --git-dir=$HOME/repos/dotfiles/ --work-tree=$HOME" \
	dot="/usr/bin/git --git-dir=$HOME/repos/dotfiles/ --work-tree=$HOME"


command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d" # Use neovim if available

