#!/bin/sh

date '+(%a) %d.%m.%Y %H:%M%p'

case $BLOCK_BUTTON in
	1) pgrep -x dunst >/dev/null && notify-send -a "This Month" "$(cal --color=always)" ;;
	2) "$TERMINAL" -e calcurse -D ~/.config/calcurse ;;
esac
