#!/bin/sh

# i3blocks module for pacman upgrades.
# Displays number of upgradeable packages.
# For this to work, have a `pacman -Sy` command run in the background as a
# cronjob every so often as root. This script will then read those packages.
# When clicked, it will run an upgrade via pacman.

case $BLOCK_BUTTON in
	1) notify-send -a "Upgradeable packages" "$(/usr/bin/pacman -Qu)" ;;
	3) $TERMINAL -e pikaur -Syu --noconfirm && pikaur -Scc && pkill -RTMIN+8 i3blocks ;;
esac


pacman -Qu | grep -v "\[ignored\]" | wc -l | sed -e "s/^0$//g"
