#!/bin/sh

tasks=$(cat "$TASKSFILE")
last_char=${tasks#"${tasks%?}"}

case $BLOCK_BUTTON in
	1) notify-send -a "Tasks" "$tasks" ;;
	2) $TERMINAL -e wunderline done && update_tasks
esac

if [ "$last_char" = '.' ]
	then
		echo 0
	else
		echo "$tasks" | wc -l
	fi
