#!/bin/sh

lock() {
    i3lock -i $LOCKBG
}

lock_blurred() {
    BLURTYPE="2x8" # 2.90s
    SCREENSHOT="scrot -o $LOCKBG" # 0.46s
    $SCREENSHOT
    convert $LOCKBG -resize 50%
    convert $LOCKBG -blur $BLURTYPE $LOCKBG
    convert $LOCKBG -resize 200%
    i3lock -i $LOCKBG
}

case "$1" in
    lock)
        lock_blurred
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
		lock_blurred && systemctl suspend
        ;;
    reboot)
        reboot
        ;;
    shutdown)
        poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
