#!/bin/sh

MAIN="LVDS-1"
CONNECTED=$(xrandr -q | grep " connected" | grep -v "$MAIN" | cut -d ' ' -f1)
NR_MON=$(xrandr -q | grep " connected" | cut -d ' ' -f1 | wc -l)

if [ "$NR_MON" -eq 2 ]; then
	echo "Activating $CONNECTED"
    xrandr --output "$MAIN" --off --output "$CONNECTED" --auto --primary
elif [ "$NR_MON" -eq 3 ]; then	
    for m in $CONNECTED; do
        xrandr --output "$m" --off
    done
    xrandr --output "$(xrandr -q | grep " connected" | grep -v "LVDS-1" | cut -d ' ' -f1 | head -n1)" --primary --auto
    xrandr --output "$(xrandr -q | grep " connected" | grep -v "LVDS-1" | cut -d ' ' -f1 | tail -n1)" --auto
else
	echo "Activating $MAIN"
    xrandr --output "$MAIN" --primary --auto
fi
