#!/bin/sh
# Starts the specified process and focus the corresponding window if it
# is already running.
#
# Parameter 1: process name

# get running programs
#programs=$(i3-msg -t get_tree | egrep -o "(class.:.[a-Z-]+.)" | sed 's/"//g;s/class://g')

pid=$(pgrep -x "$1")

if [ -z "$pid" ]; then
    $1 &
    sleep 0.8
fi

# focus program
i3-msg "[instance="$1"] focus"

