#!/bin/sh

MONITOR=$(xrandr -q | grep " connected" | grep -v "LVDS1" | cut -d ' ' -f1 | head -n 1)
STATUS=$(xprop -name polybar-base_$MONITOR WM_STATE | grep "window state" | awk -F ':' '{print $2}' | sed -e 's/^[[:space:]]*//')

if [ "$STATUS" = "Withdrawn" ]; then
    xdo show -N Polybar
else
    xdo hide -N Polybar
fi
