#!/bin/sh
# Syncs repositories and downloads updates, meant to be run as a cronjob.

ScriptsDir=/home/daniel/.scripts

ping -q -c 1 1.1.1.1 > /dev/null || exit

"$ScriptsDir"/notify-all -a "📦 Repository Sync" "Checking for package updates..."

sudo pikaur -Syyuw --noconfirm || "$ScriptsDir"/notify-all -a "📦 Repository Sync" "Error downloading updates. Check your internet connection, if pacman is already running, or run update manually to see errors."
pkill -RTMIN+8 i3blocks

if pikaur -Qu | grep -v "\[ignored\]"
then
	"$ScriptsDir"/notify-all -a "🎁 Repository Sync" "Updates available. Click statusbar icon (📦) for update."
else
	"$ScriptsDir"/notify-all -a "📦 Repository Sync"  "Sync complete. No new packages for update."
fi
