#!/bin/sh

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

if type "xrandr"; then
  for m in $(xrandr --listactivemonitors | awk '{print $NF}' | sed -n '1!p'); do
    MONITOR=$m polybar --reload -c ~/.config/polybar/config base &
  done
else
  polybar --reload base &
fi

echo "Bars launched..."